
spring:
  security:
    basic:
      url: http://localhost:8083
    jwt:
      url: http://localhost:8084
      username: "han.do@example.com"
      password: "12345"
    user:
      name: "user"
      password: "12345"


logging:
  level:
    com.springboot.cloud.openfeign.interceptor.service.api: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel: full
