
server:
  port: 8086

spring:
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  security:
    basic:
      url: http://localhost:8083
      username: "user"
      password: "12345"
      token: "Basic dXNlcjoxMjM0NQ=="
    jwt:
      url: http://localhost:8084
      credentials:
        username: "han.do@example.com"
        password: "12345"
    oauth2:
      url: http://localhost:8085
      client:
        registration:
          keycloak: # <--- It's your custom client. I am using keycloak
            client-id: myclient
            client-secret: 80YlNd6qwz84hnisibF8QHVAtjUkVj0p
            authorization-grant-type: client_credentials
            scope: # your scopes
              - openid
              - address
              - email
              - profile
        provider:
          keycloak: # <--- Here Registered my custom provider
            authorization-uri: http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/auth
            token-uri: http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/token


logging:
  level:
    com.springboot.cloud.openfeign.interceptor.service.api: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel: full