
server:
  port: 8086

spring:
  security:
    basic:
      url: http://localhost:8083
      username: "user"
      password: "12345"
      token: "Basic dXNlcjoxMjM0NQ=="
    jwt:
      url: http://localhost:8084
      credentials:
        username: "han.do@example.com"
        password: "12345"

logging:
  level:
    com.springboot.cloud.openfeign.interceptor.service.api: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel: full