server:
  port: 8080

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  application:
    name: sleuth-zipkin-customer-service
  cloud:
    discovery:
      enabled: true
  sleuth:
    sampler:
      probability: 1.0
    # propagation:
    #   type: B3,W3C
    supports-join: false    
  opentracing:
    enabled: true
  zipkin:
    kafka:
      topic: zipkin
    sender:
      type: kafka
#    base-url: http://localhost:9411


logging:
  level:
    root: INFO
#    org:
#      springframework:
#        cloud:
#          sleuth: DEBUG

product:
  service:
    name: sleuth-zipkin-product-service
