
#server run at port 8761
server:
  port: 8761

spring:
  application:
    #application name
    name: eureka-server
  sleuth:
    sampler:
      percentage: 1.0
    propagation:
      type: B3,W3C
  opentracing:
    enabled: true
  zipkin:
    base-url: http://localhost:9411


logging:
  level:
    root: INFO
#    org:
#      springframework:
#        cloud:
#          sleuth: DEBUG


eureka:
  client:
    #self register is false
    register-with-eureka: false
    #self fetch registry is false
    fetch-registry: false
