server:
  port: 8080

spring:
  application:
    name: jaeger-adapter-service
  sleuth:
    enabled: true
    tracing:
      otlp:
        endpoint: "http://localhost:4317"
    #      baggage:
    #        remote-fields: <comma-separated-list-of-fields-to-propagate>
    sampler:
      probability: 1.0

logging:
  level:
    root: INFO
    io.opentelemetry: INFO