server:
  port: 8080

spring:
  application:
    name: jaeger-adapter-service
  sleuth:
    enabled: true
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          enabled: true
          endpoint: http://localhost:4317
        jaeger:
          enabled: false
      log:
        exporter:
          enabled: true
        slf4j:
          enabled: true

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          sleuth: DEBUG
