
#server run at port 8761
server:
  port: 8761

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  application:
    #application name
    name: eureka-server
  sleuth:
    sampler:
      probability: 1.0
    # propagation:
    #   type: B3,W3C
    supports-join: true
    trace-id128: true
  opentracing:
    enabled: true
  zipkin:
    kafka:
      topic: zipkin
    sender:
      type: kafka
#    base-url: http://localhost:9411


logging:
  level:
    root: INFO
#    org:
#      springframework:
#        cloud:
#          sleuth: DEBUG


eureka:
  client:
    #self register is false
    register-with-eureka: false
    #self fetch registry is false
    fetch-registry: false
