
#server run at port 8761
server:
  port: 8761

spring:
  application:
    #application name
    name: eureka-server
  sleuth:
    enabled: true
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          enabled: true
          endpoint: http://localhost:4317
        jaeger:
          enabled: false
      log:
        exporter:
          enabled: true
        slf4j:
          enabled: true

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          sleuth: DEBUG


eureka:
  client:
    #self register is false
    register-with-eureka: false
    #self fetch registry is false
    fetch-registry: false
