#service run at port 9090
server:
  port: 9090

spring:
  application:
    #service name which will be showed on eureka server dashboard
    name: jaeger-bff-application-service
  #Enable Spring Cloud Discovery
  cloud:
    discovery:
      enabled: true
  sleuth:
    enabled: true
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          enabled: true
          endpoint: http://localhost:4317
        jaeger:
          enabled: false
      log:
        exporter:
          enabled: true
        slf4j:
          enabled: true

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          sleuth: DEBUG

#register this service to eureka server by url
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

adapter:
  service:
    name: jaeger-adapter-service
