
server:
  port: 8081

spring:
  mandatory-file-encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
  application:
    name: openfeign-openapi-server
  cloud:
    discovery:
      enabled: true
    loadbalancer:
      retry:
        enable: true
        maxRetriesOnSameServiceInstance: 5
        backoff:
          maxBackoff: 5000
  datasource:
    url: jdbc:h2:file:./testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
#    naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true