
server:
  port: 8080

spring:
  application:
    name: blog-adapter-service
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:h2:file:./testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

management:
  endpoint:
    health:
      show-details: always



post:
  page:
    size: 5
    defaultKey: createdDate